[package]
name = "the-cleaners"
version = "0.1.0"
edition = "2021"

[dependencies]
turbo = { version = "*", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[workspace]
members = ["map-compiler"]
resolver = "2"
