use crate::{
    vec2, BloodLevel, BodyLevel, Furniture, Item, Tile, TileBackground, Vec2, BODY_CHOPPING_TIME,
    CLEANING_TIME,
};

pub fn create_level_0() -> (Vec<Vec<Tile>>, Vec2) {
    (
        vec![
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Floor(vec2(0, 8)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::Wall(vec2(11, 0)),
                    foreground: None,
                    item: Item::Sponge,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::Tall(CLEANING_TIME),
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::Tall(CLEANING_TIME),
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::Wall(vec2(11, 6)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 13)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(10, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Floor(vec2(0, 8)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::Wall(vec2(9, 0)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::Tall(CLEANING_TIME),
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::Grande(CLEANING_TIME),
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::Floor(vec2(10, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(5, 6)),
                    furniture: Furniture::None,
                    foreground: Some(vec2(5, 6)),
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(10, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(8, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::Wall(vec2(13, 4)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::Body(BodyLevel::Start, BODY_CHOPPING_TIME),
                    player: false,
                    blood_level: BloodLevel::Venti(CLEANING_TIME),
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 13)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::Wall(vec2(4, 10)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Floor(vec2(0, 8)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 4)),
                    furniture: Furniture::Wall(vec2(15, 4)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::Wall(vec2(8, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::Floor(vec2(10, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(5, 6)),
                    furniture: Furniture::None,
                    foreground: Some(vec2(5, 6)),
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: Some(vec2(5, 9)),
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::Wall(vec2(5, 10)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(2, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(2, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(2, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 13)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: Some(vec2(6, 9)),
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::Wall(vec2(6, 10)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: true,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(12, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(12, 6)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::Bleach,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 3)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 13)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(10, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(8, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(12, 6)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Floor(vec2(9, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Wall(vec2(15, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(10, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: true,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(2, 12)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(12, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(13, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::Wall(vec2(12, 0)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(5, 6)),
                    furniture: Furniture::None,
                    foreground: Some(vec2(5, 6)),
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(10, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(12, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(10, 0)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Wall(vec2(11, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Wall(vec2(11, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 13)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(10, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(12, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(17, 4)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(5, 6)),
                    furniture: Furniture::None,
                    foreground: Some(vec2(5, 6)),
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(8, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(16, 4)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Wall(vec2(10, 2)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 13)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::Wall(vec2(4, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: true,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(12, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(14, 6)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Wall(vec2(10, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Wall(vec2(12, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::Wall(vec2(12, 1)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 1)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::Floor(vec2(12, 5)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(6, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(6, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(6, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::BodyBag,
                    player: false,
                    blood_level: BloodLevel::Venti(CLEANING_TIME),
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Wall(vec2(5, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(12, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(17, 4)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::Wall(vec2(5, 2)),
                    foreground: None,
                    item: Item::Knife,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 5)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(3, 2)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::BagRoll,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(3, 13)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(12, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Floor(vec2(7, 3)),
                    furniture: Furniture::Floor(vec2(4, 3)),
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
            vec![
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
                Tile {
                    background: TileBackground::Wall(vec2(9, 6)),
                    furniture: Furniture::None,
                    foreground: None,
                    item: Item::None,
                    player: false,
                    blood_level: BloodLevel::None,
                    drop_point: false,
                },
            ],
        ],
        vec2(7, 13),
    )
}
