use crate::{vec2, BloodLevel, Item, Tile, TileBackground};

pub fn create_level_0() -> Vec<Vec<Tile>> {
    vec![
        vec![
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Floor(vec2(0, 8)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(11, 0)),
                item: Item::Sponge,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::Tall,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::Tall,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(11, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(3, 13)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Floor(vec2(0, 8)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 0)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::Tall,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::Grande,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(5, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(8, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::Venti,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(3, 13)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(4, 10)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Floor(vec2(0, 8)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(15, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(8, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(5, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(5, 10)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Floor(vec2(2, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(2, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(2, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(3, 13)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(6, 10)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(12, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(12, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 5)),
                item: Item::Bleach,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(3, 13)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(8, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(12, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 5)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Floor(vec2(2, 12)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(12, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 5)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(13, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(12, 0)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(5, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(12, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(10, 0)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 5)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(11, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(11, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(3, 13)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(12, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(17, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 5)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(5, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(8, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(16, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 5)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(10, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(3, 13)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(12, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(14, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 5)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(10, 3)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(12, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(12, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 1)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(12, 5)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(6, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(6, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(6, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(12, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(17, 4)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(5, 2)),
                item: Item::Knife,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(3, 2)),
                item: Item::BagRoll,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(3, 13)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Floor(vec2(7, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(8, 3)),
                item: Item::BodyBag,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
        vec![
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
            Tile {
                background: TileBackground::Wall(vec2(9, 6)),
                item: Item::None,
                player: false,
                blood_level: BloodLevel::None,
            },
        ],
    ]
}
